import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { ArrowRight, CheckCircle2, CircleAlert, FileCheck2, GitBranch, GraduationCap, Pencil, ShieldCheck, Target } from "lucide-react";
import { Workspace } from "@/pages/Workspace";
import { apiGet } from "@/lib/api";
import type { Dashboard, EligibilityResult, Profile } from "@/lib/types";
import { Button } from "@/components/ui/button";

const money = (value: number) => `₹${(value / 100000).toFixed(1)} lakh`;
const academicScore = (profile: Profile) => profile.score_type === "Percentage" ? `${profile.score_value}%` : profile.score_type === "Grade" ? `${profile.score_value} grade` : `${profile.score_value} ${profile.score_type} / ${profile.score_scale}`;

export default function StudentDashboard() {
  const navigate = useNavigate();
  const query = useQuery({ queryKey: ["dashboard"], queryFn: () => apiGet<Dashboard>("/dashboard"), retry: false });
  if (query.isPending) return <Workspace view="dashboard"><StatePanel text="Loading your decision workspace…" /></Workspace>;
  if (query.error || !query.data) return <Workspace view="dashboard"><StatePanel error text="Unable to load the dashboard. Please sign in again." /></Workspace>;
  const data = query.data;
  const top = data.scholarships.filter((item) => item.overall_status !== "NOT_ELIGIBLE").slice(0, 3);
  return <Workspace view="dashboard">
    <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-teal-700">Student command center</p><h1 data-testid="page-heading" className="mt-2 font-heading text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Welcome, {data.profile.full_name}</h1><p className="mt-2 text-sm leading-6 text-slate-600">Your profile, scholarship decisions, and next actions in one place.</p></div><Button data-testid="dashboard-profile-button" variant="outline" onClick={() => navigate("/profile")}><Pencil /> Edit profile</Button></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric testid="dashboard-potential-matches" label="Potential matches" value={data.matched_count} detail="profile-fit and review records" tone="teal" /><Metric testid="dashboard-eligible-count" label="Eligible now" value={data.eligible_count} detail="stored criteria match" /><Metric testid="dashboard-review-count" label="Needs review" value={data.review_count} detail="official check recommended" tone="amber" /><Metric testid="dashboard-documents-ready" label="Documents ready" value={`${data.documents_ready}/${data.documents_total}`} detail={data.action_count ? "one or more missing" : "current checklist"} tone={data.action_count ? "rose" : "teal"} /></div>
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><Panel><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-teal-700">Scholarships to review</p><h2 className="mt-1 font-heading text-xl font-extrabold text-slate-950">Your strongest matches</h2></div><Button data-testid="dashboard-view-scholarships-button" variant="ghost" onClick={() => navigate("/scholarships")} className="text-teal-700">View all <ArrowRight /></Button></div><div className="mt-5 space-y-3">{top.map((item) => <ScholarshipRow key={item.scholarship.id} item={item} onClick={() => navigate(`/scholarships/${item.scholarship.id}`)} />)}</div></Panel><Panel><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-xl bg-amber-100 text-amber-700"><Target className="size-5" /></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-amber-700">Your next actions</p><h2 className="mt-1 font-heading text-xl font-extrabold text-slate-950">Keep moving</h2></div></div><div className="mt-5 space-y-4">{data.next_actions.map((action, index) => <button data-testid={`dashboard-next-action-${index + 1}`} key={action} onClick={() => navigate(index === 0 ? "/documents" : index === 1 ? "/compare" : "/readiness")} className="flex w-full items-start gap-3 text-left text-sm font-semibold text-slate-700 hover:text-teal-700"><span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-slate-100 font-mono text-[10px] text-slate-500">{index + 1}</span><span>{action}</span><ArrowRight className="ml-auto mt-0.5 size-4 shrink-0" /></button>)}</div><Button data-testid="dashboard-quick-compatibility-button" onClick={() => navigate("/compare")} className="mt-6 w-full bg-slate-950 text-white hover:bg-teal-700">Check compatibility <GitBranch /></Button></Panel></div>
    <div className="mt-6 grid gap-6 lg:grid-cols-3"><Panel className="lg:col-span-2"><div className="flex items-center justify-between gap-3"><h2 className="font-heading text-lg font-extrabold text-slate-950">Your profile</h2><span data-testid="dashboard-profile-type" className="rounded-full bg-teal-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider text-teal-700">{data.profile.user_id === "demo-aarav" ? "Fictional demo student" : "Personal profile"}</span></div><div className="mt-5 grid gap-4 text-sm sm:grid-cols-4"><ProfileStat label="Course" value={`${data.profile.course || "Not provided"} · ${data.profile.branch || "Not provided"}`} /><ProfileStat label="Academic" value={`${data.profile.education_level} · ${data.profile.year || "Year not provided"} · ${academicScore(data.profile)}`} testid="dashboard-academic-score" /><ProfileStat label="State" value={data.profile.state || "Not provided"} /><ProfileStat label="Family income" value={money(data.profile.annual_income)} /></div></Panel><Panel><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-teal-700">Responsible guidance</p><p className="mt-3 text-sm leading-6 text-slate-600">CGPA, SGPA, and grades are never automatically converted to a percentage. Percentage-based rules remain Review until an official conversion is available.</p><button data-testid="dashboard-open-profile-score-button" onClick={() => navigate("/profile")} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-teal-700">Review academic score <ArrowRight className="size-4" /></button></Panel></div>
  </Workspace>;
}

function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</div>; }
function Metric({ label, value, detail, tone = "slate", testid }: { label: string; value: number | string; detail: string; tone?: "slate" | "teal" | "amber" | "rose"; testid: string }) { const color = { slate: "border-slate-200 bg-white", teal: "border-teal-200 bg-teal-50", amber: "border-amber-200 bg-amber-50", rose: "border-rose-200 bg-rose-50" }[tone]; return <div data-testid={testid} className={`rounded-2xl border p-5 ${color}`}><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-3 font-heading text-3xl font-extrabold text-slate-950">{value}</p><p className="mt-1 text-xs font-semibold text-slate-500">{detail}</p></div>; }
function ProfileStat({ label, value, testid }: { label: string; value: string; testid?: string }) { return <div data-testid={testid}><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-slate-800">{value}</p></div>; }
function ScholarshipRow({ item, onClick }: { item: EligibilityResult; onClick: () => void }) { const eligible = item.overall_status === "ELIGIBLE"; return <button data-testid={`dashboard-scholarship-${item.scholarship.id}`} onClick={onClick} className="flex w-full items-center gap-4 rounded-xl border border-slate-200 p-4 text-left hover:border-teal-300"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-slate-950 text-teal-300"><GraduationCap className="size-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900">{item.scholarship.name}</p><p className="mt-1 truncate text-xs text-slate-500">{item.scholarship.provider}</p></div><span className={`flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-extrabold uppercase ${eligible ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{eligible ? <CheckCircle2 className="size-3" /> : <CircleAlert className="size-3" />}{eligible ? "Eligible" : "Review"}</span></button>; }
function StatePanel({ text, error = false }: { text: string; error?: boolean }) { return <div data-testid={error ? "dashboard-error-state" : "dashboard-loading-state"} className={`rounded-2xl border p-10 text-center text-sm font-semibold ${error ? "border-rose-200 bg-rose-50 text-rose-700" : "border-slate-200 bg-white text-slate-500"}`}>{error ? <CircleAlert className="mx-auto mb-3 size-6" /> : <FileCheck2 className="mx-auto mb-3 size-6 text-teal-700" />}{text}</div>; }